### ISSUE TITLE
Package Deployment Issue

### ISSUE THREAD

**Issue by mswbull** [tyoshikawa1106/lightning-skill-checker#1]
Package fails to deploy to DE Org. Error message:

Apex class 'SkillCheckerController' does not exist  SkillChecker: Apex class 'SkillCheckerController' does not exist
Entity is not org-accessible    SkillCheckerHelper: Entity is not org-accessible
Entity is not org-accessible    SkillCheckerWrapper: Entity is not org-accessible
Entity is not org-accessible    SkillCommonTester: Entity is not org-accessible
No CONTROLLER named apex://SkillCheckerController found : No CONTROLLER named apex://SkillCheckerController found
Entity is not org-accessible    SkillCommonTesterTest: Entity is not org-accessible

**Comment by tyoshikawa1106** [comment]
@mswbull 
Oh...I take a look.
Thanks!

**Comment by tyoshikawa1106** [comment]
@mswbull 
OK! Please activate the Skills of Work.com Setting.

<img src="http://f.st-hatena.com/images/fotolife/t/tyoshikawa1106/20150718/20150718175336.png?1437209733" />

<img src="http://f.st-hatena.com/images/fotolife/t/tyoshikawa1106/20150718/20150718175337.png?1437209754" />

You can be installed in this.
Thanks!!

**Comment by mswbull** [comment]
Perfect, thanks. Works great!
